"""demo/run_demo.py — the 3-minute demo state machine. Keyboard-stepped, never auto-advances.

===============================================================================
DEMO_RUNBOOK  (read this before you go on stage)
===============================================================================

*** THE GOLDEN PATH — this is the demo. It is the DEFAULT when you run with no
*** flags. Everything below it is options, fallbacks and history.

    .venv/bin/python demo/run_demo.py

  1. The arm plays 'wake' (~20s showcase) and it greets you with the corpus size.
  2. YOU SAY:  "fold a piece of paper"
     -> computed: tier=abstain. "fold" IS covered (it has seen folding work);
        "piece" and "paper" are NOT. Nearest real task: Binding Pre Fold Stitching.
     -> arm plays 'decline', and it refuses and ENDS WITH "How do I do it?"
  3. YOU DESCRIBE how to fold paper, out loud, for 6 seconds. Anything you like.
     -> arm plays 'attempt' and it tries.
     -> it closes honestly: it heard N words, it still has 0 demonstrations.
        The attempt NOT succeeding is the point. Do not apologise for it.
  4. THE CAN BEAT — hold up a drinks can and say "put this can upside down".
     -> computed: tier=abstain, coverage 0.0 (NOT ONE content word is known).
     -> arm plays 'approach_can' and hovers over it.
     -> it asks whether to hold the can at the TOP or the BOTTOM.
     -> YOU ANSWER out loud. "top" -> can_grip_top; "bottom"/"base"/"side" ->
        can_grip_bottom. Unrecognised -> it asks once more, then defaults to top
        and SAYS that it defaulted.
     -> the chosen grip runs (top rolls the wrist and turns the can over), then
        the same honest close: N words heard, still 0 demonstrations.
     THE GRIP IS CHOSEN BY KEYWORD MATCH, NOT BY THE LLM. Say that out loud —
     it is the cleanest demonstration that the model cannot move the arm.
  5. It stays in the conversation loop. Judges can ask it anything — every query
     gets a computed answer, including ones that are not tasks at all.

  The one line to say out loud early:
     "It is not refusing because it is unsure. It is refusing because it counted."

LAUNCH — from the USER'S OWN Terminal.app, not from a Claude/agent session.
Terminal.app already holds macOS Camera permission; agent-spawned processes do
not (FACTS.md WEBCAM_STATUS=blocked), and BEAT 4 needs the webcam.

    cd /Users/tarunyadgirkar/TarunsCode/hackathons/Robotics-Hackathon-project
    DS_VIDEOS=/Users/tarunyadgirkar/TarunsCode/ds-hack ARM_SIM_RENDER=0 \
      .venv/bin/python demo/run_demo.py

(run_demo sets both of those itself if they are unset — the explicit form above
is just so you can see what is going on. ARM_SIM_RENDER=0 skips the ~2s/motion
GIF render; the stills in arm/sim_out/ are already rendered for the screen.)

Useful flags:
    (no flags)       the GOLDEN PATH above — this is what you run on stage
    --scripted       DETERMINISTIC BACKUP: no mic, no LLM, no network (see below)
    --converse       skip the wake/greeting, go straight to free conversation
    --beats          the original scripted 4-beat sequence
    --text-mode      start in typed-input mode (loud room; you can also switch live)
    --no-llm         force fixed templates, never call the LLM phrasing layer
    --no-audio       render + print the spoken text without playing it
    --beat N         with --beats, start at beat N (1-4)
    --sim-arm        print what the arm would do instead of commanding it
    --build-cache    re-synthesize the scripted backup's audio, then exit
    --rehearse       drive every mode through --text end-to-end, non-interactively

SCRIPTED BACKUP (--scripted) — the judge explicitly sanctioned a hardcoded demo
AS A BACKUP. It is labelled "[SCRIPTED BACKUP]" in the terminal throughout so
nobody is misled, and you should say the word "backup" out loud when you use it.
It touches NOTHING external: no microphone, no LLM, no network, no ElevenLabs
call. It plays pre-synthesized mp3s from demo/audio_cache/ with afplay.
The numbers in that cached audio are still real — the decision JSONs in
demo/decisions/scripted/ were generated by the real brain/decide.py.
MOTION CUE POINTS (deterministic order, one SPACE each):
    SPACE 1  gesture 'wake'     -> cached greeting audio
    SPACE 2  gesture 'decline'  -> cached refusal audio   (you say "fold a piece
                                   of paper" just before pressing)
    SPACE 3  gesture 'attempt'  -> cached close audio     (you mime describing
                                   how, for ~6s, just before pressing)
    SPACE 4  gesture 'approach_can' -> cached can question (hold up the can and
                                   say "put this can upside down" just before)
    SPACE 5  gesture 'can_grip_top' -> cached can close    (say "hold it at the
                                   top" just before pressing)
Re-run `--build-cache` if any template or the corpus changes, otherwise the
cached audio and the live numbers can drift apart.

THE ARM MAY DIE — AND THE DEMO WILL NOT. Every gesture/replay/home call in every
mode (golden path, converse, beats, scripted) is wrapped: if the arm raises
anything at all, the terminal prints
    [ARM OFFLINE — continuing without motion]
and the spoken line and evidence panel carry on uninterrupted. It is deliberately
NOT latched — Agent C's auto-reconnect may bring the arm back, so every later
motion tries again. If the arm dies mid-demo, say "the arm is offline, the
reasoning is not" and keep going; nothing else about the demo changes.

KEYS (single keypress, no Enter):
    SPACE   advance to the next step. A beat never starts without this.
    n       same as SPACE (in case the space bar is awkward on a podium)
    t       toggle input mode SPOKEN <-> TYPED, mid-demo, without breaking flow.
            This is the stage fallback for room noise. Same code path either way
            (listen/transcribe.py --text), so nothing else changes. It also
            covers the spoken REPLIES in beats 2 and 3, not just the queries.
    r       re-run the current step (e.g. STT misheard you)
    h       recover-home after a freeze (asks the arm for a second confirmation)
    q       quit. Arm is left where it is; it is not homed behind your back.

ARM MOTIONS ARE NO LONGER INDIVIDUALLY GATED (user override). A motion runs when
its beat's logic decides to run it — which now includes running in response to a
SPOKEN REPLY in beat 2. SPACE still gates the start of every step, and the
terminal prints a red ">>> ARM MOVING NOW <<<" banner immediately before any
motion. Ctrl-C during a motion FREEZES AND HOLDS — it does not home. Press 'h'
afterwards to home at 25% speed. Keep the workspace clear for the whole demo,
not just around the keypresses.

HUMAN-IN-THE-LOOP RESOLUTION (beats 2 and 3). The point is ambiguity that YOU
resolve out loud, not the robot merely declining:
    beat 2  it asks majority-vs-outlier, then WAITS for your reply.
            "go on" / "yes" / "majority" / "continue"  -> it executes the motion
            "stop" / "no" / "wait" / "hold"            -> it holds and says
                                                          "Holding. 9 demonstrations
                                                           remain unexecuted."
    beat 3  the refusal ENDS with "How do I do it?" — then it listens for 6s while
            you TELL it how, in plain speech. Then it ATTEMPTS: the arm runs the
            'attempt' motion, and the close reports honestly what actually
            happened — that it received N words of instruction and still has zero
            demonstrations. It never claims the attempt worked.
            Told (beat 3) then shown (beat 4) is the escalation arc; the honest
            boundary is that neither one gives it a demonstration it can replay.
Replies are classified by token overlap against two fixed word sets — no LLM. A
reply matching both sets or neither is treated as unrecognized: the robot says it
did not understand and re-listens, twice, then switches to a typed prompt. When
intent is unclear it asks again rather than guessing and moving.

LLM PHRASING (converse + golden path). An LLM chooses the WORDS. It does not
choose anything else, and it CANNOT MOVE THE ARM:

    listen/transcribe.py   speech in       local Whisper, no network
    brain/decide.py        THE DECISION    tier + evidence, computed from the
                                           corpus. This is the ground truth.
    voice/llm_phrase.py    wording only    hard-constrained by system prompt to
                                           the decision JSON: numbers verbatim,
                                           no task names not in the JSON, no
                                           invented capabilities, tier semantics
                                           not negotiable
    voice/speak.py         speech out      TTS

Motion is driven by the computed tier in respond_to(); the LLM's output is never
read for control. That is the safety answer AND the contest-rules answer: the
decision is real and computed, the LLM only says it nicely.
Each line is tagged [llm] or [template] in the terminal so you can see which
phrased it. If the call errors or exceeds ~2s the fixed template is used for that
turn — the templates are the reliability floor, not a legacy path. --no-llm
forces templates everywhere.

SAY OUT LOUD, EARLY (the state machine prints this too, at start):
    "The numbers are computed live from the corpus. The wording may be phrased by
     a small model, but it can only say what the decision JSON already contains —
     and it cannot move the arm."

BACKUP VIDEO — record this yourself before the demo (a human must do this;
it cannot be automated from an agent session):
    1. QuickTime Player > File > New Screen Recording. Record the whole screen
       (not a window) so the evidence panels are captured. Enable the microphone
       input in the record menu so your narration lands on the same track.
    2. Point a phone at the laptop screen / arm area as a second angle.
    3. Start both recordings, then run the launch command above and do a clean
       full pass of all 4 beats, narrating exactly as you will on stage.
    4. Stop, trim the head/tail in QuickTime (Edit > Trim), export 1080p.
    5. Keep it UNDER 3 MINUTES. Upload to YouTube unlisted, put the link in the
       submission form and in BUILD_CARD.md.
    6. Do this BEFORE any further code changes. It is the non-negotiable
       fallback if the live demo dies on stage.

BEATS
    1  act      "garment iron press"   -> tier=act    -> arm replays, says nothing
    2  ask      "garment inside out"   -> tier=ask    -> majority (8) vs outlier (1)
    3  abstain  "do a bottle flip"     -> refuses, ASKS HOW, you tell it, it tries
    4  feedback ingest 3 live takes    -> abstain-after-feedback, cites live numbers

BEAT 3 speaks D's 'abstain_howto' and 'attempt_result' templates; run_demo passes
them by name via speak.py --template and supplies the computed slots
(instruction_words, instruction_chars, n_matching_demos) by merging them into a
copy of the decision JSON. If a template is not in voice/speak.py yet, the beat
degrades to the tier's default line and prints a PENDING warning rather than dying.
The 'attempt' motion falls back to task_demo until arm/gestures/.../attempt.json
exists; the fallback is announced in the terminal so you can disclose it on stage.

TIMING — measured on the F rehearsal, machine time only (no keypress pauses):
    home 0.6s | beat1 19.4s | beat2 45.3s | beat3 28.1s | beat4 35.2s  => ~2m09s
Speech is the second cost after the arm: ElevenLabs synthesis is sub-second, but
afplay then plays the whole utterance (beat2 22.5s, beat3 20.7s, beat4 27.8s).
Add BEAT 4's real recording (3 takes, ~30-60s) and you are OVER 3 minutes.
Cut order if you are long, per PLAN_v2, cutting from the top:
    1. BEAT 2's task_demo replay (-19.4s) — keep the gesture, voice and screen
    2. BEAT 1 entirely (-19.4s)
BEAT 3 and BEAT 4 are never cut.

BEAT 4 records from the webcam. If the camera is not authorized, ingest exits 1
with an actionable message and the state machine tells you to fall back to
narrating the beat instead of dying. Grant Camera to Terminal.app in
System Settings > Privacy & Security > Camera before the demo.
===============================================================================
"""
import argparse
import json
import os
import subprocess
import sys
import termios
import time
import tty
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
PY = str(REPO_ROOT / ".venv" / "bin" / "python")

os.environ.setdefault("DS_VIDEOS", "/Users/tarunyadgirkar/TarunsCode/ds-hack")
os.environ.setdefault("ARM_SIM_RENDER", "0")  # live path: no per-motion GIF render

sys.path.insert(0, str(REPO_ROOT))

DECISION_DIR = REPO_ROOT / "demo" / "decisions"
PANEL_DIR = REPO_ROOT / "demo" / "panels"

BEAT1_QUERY = "garment iron press"
BEAT2_QUERY = "garment inside out"
BEAT3_QUERY = "do a bottle flip"

DISCLOSURE = (
    "The sentences are fixed templates. Every number inside them is computed live "
    "from the corpus, right now, on this machine."
)

BOLD = "\033[1m"
DIM = "\033[2m"
CYAN = "\033[36m"
YEL = "\033[33m"
RED = "\033[31m"
GRN = "\033[32m"
OFF = "\033[0m"


class Quit(Exception):
    pass


class State:
    def __init__(self, args):
        self.text_mode = args.text_mode or args.rehearse
        self.rehearse = args.rehearse
        self.no_audio = args.no_audio
        self.transcript = []
        self.panel_proc = None
        self.sim_arm = args.sim_arm
        self.use_llm = not args.no_llm
        self.history = []
        # Rehearsal-only scripted replies, keyed by the capture label. This is how
        # --rehearse walks BOTH the negative and affirmative resolution branches
        # (and the unrecognized-retry path) through the same --text code path the
        # stage fallback uses.
        self.scripted = {
            "beat2-reply": "mmhrgh",          # unrecognized -> robot re-asks
            "beat2-reply1": "stop",           # negative     -> arm holds
            "beat2b-reply": "go on",          # affirmative  -> arm executes
            "beat3-instruction": INSTRUCTION_FALLBACK,  # the human teaches it out loud
            "converse2-reply": "go on",            # ask tier resolution in converse
            "converse3-instruction": INSTRUCTION_FALLBACK,
            "converse2-grip": "hold it at the top",
            "can-grip": "hold it at the top",
        }
        # Rehearsal-only converse pass: an act task, an ask task, an abstain task,
        # and a gibberish turn that must still get a spoken response.
        self.converse_script = [
            "garment iron press",
            "garment inside out",
            "do a bottle flip",
            "wubbalubba dubdub",
        ]
        # BEAT 3's exact transcript string is reused verbatim as BEAT 4's ingest
        # --task and as the --include-live query. feedback/live_index.json is keyed
        # on the raw query string, so anything less than verbatim reuse silently
        # produces a live-index miss and BEAT 4 degrades to a plain abstain.
        self.beat3_query = None

    def log(self, line):
        self.transcript.append(line)


# --------------------------------------------------------------------------- io

def say(msg=""):
    print(msg, flush=True)


def banner(text, color=CYAN):
    say()
    say(f"{color}{'=' * 78}{OFF}")
    say(f"{color}{BOLD}{text}{OFF}")
    say(f"{color}{'=' * 78}{OFF}")


def read_key():
    """One keypress, no Enter. cbreak is entered and left around each read so
    subprocesses (transcribe's push-to-talk, ingest's cv2 window) get a normal
    terminal."""
    if not sys.stdin.isatty():
        ch = sys.stdin.read(1)
        return ch if ch else "q"
    fd = sys.stdin.fileno()
    old = termios.tcgetattr(fd)
    try:
        tty.setcbreak(fd)
        return sys.stdin.read(1)
    finally:
        termios.tcsetattr(fd, termios.TCSADRAIN, old)


def gate(st, prompt, is_motion=False):
    """Block until the operator advances. Returns 'go' or 'again'.

    Arm motions are NOT gated (operator's decision, 2026-08-30): the demo is the
    robot trying something and reacting, not a human driving it key by key. They
    run as soon as the beat reaches them, on the SPACE the operator already
    pressed for the step before. Beat pacing is unchanged — every non-motion
    step still waits — and Ctrl-C is still the e-stop, freezing and holding.
    """
    if st.rehearse:
        say(f"{DIM}[rehearse] auto-advance: {prompt}{OFF}")
        return "go"
    if is_motion:
        say(f"\n{YEL}[ARM]{OFF} {BOLD}{prompt}{OFF}")
        say(f"{DIM}  running now — Ctrl-C freezes and holds{OFF}")
        return "go"
    mark = ""
    while True:
        say()
        say(f"{mark}{BOLD}{prompt}{OFF}")
        say(f"{DIM}  SPACE/n=go  r=redo  t=input mode ({'TYPED' if st.text_mode else 'SPOKEN'})"
            f"  h=recover-home  q=quit{OFF}")
        k = read_key()
        if k in (" ", "n", "\r", "\n"):
            return "go"
        if k == "r":
            return "again"
        if k == "t":
            st.text_mode = not st.text_mode
            say(f"{GRN}  input mode -> {'TYPED' if st.text_mode else 'SPOKEN'}{OFF}")
            continue
        if k == "h":
            recover_home()
            continue
        if k == "c":
            converse(st)
            continue
        if k == "q":
            raise Quit()


def recover_home():
    from arm import arm_io, safety

    if not safety.is_frozen():
        say(f"{DIM}  arm is not frozen; nothing to recover{OFF}")
        return
    say("  arm is frozen. arm_io.recover_home() will ask you to confirm before it moves.")
    try:
        arm_io.recover_home()
    except Exception as exc:  # noqa: BLE001 - stage code, surface and continue
        say(f"{RED}  recover_home failed: {exc}{OFF}")


# ------------------------------------------------------------------- components

def capture_query(st, expected, label, seconds=None):
    """Query in through listen/transcribe.py. Spoken by default; --text is the
    identical code path, which is why the stage fallback costs nothing.

    seconds=N uses transcribe.py's fixed-duration capture instead of push-to-talk
    (BEAT 3's instruction: the human just talks for 6s, no second keypress)."""
    cmd = [PY, str(REPO_ROOT / "listen" / "transcribe.py")]
    if seconds and not st.text_mode:
        cmd += ["--seconds", str(seconds)]
        say(f"{BOLD}  speak now — {seconds}s{OFF}")
    if st.text_mode:
        typed = st.scripted.get(label, expected) if st.rehearse else expected
        if not st.rehearse:
            say(f"{DIM}  typed-input mode. Enter overrides; blank uses {expected!r}{OFF}")
            try:
                entered = input("  query> ").strip()
            except EOFError:
                entered = ""
            typed = entered or expected
        cmd += ["--text", typed]
    else:
        # timed capture, not push-to-talk: with stdout captured, the child's
        # SPACE prompt is invisible and recording never starts (found live)
        cmd += ["--seconds", "6"]
        say(f"{GRN}  LISTENING for 6 seconds — speak now{OFF}")
    out = subprocess.run(cmd, cwd=REPO_ROOT, capture_output=True, text=True)
    if out.stderr.strip():
        say(f"{DIM}{out.stderr.strip()}{OFF}")
    transcript = out.stdout.strip()
    if out.returncode != 0 or not transcript:
        say(f"{RED}  STT produced nothing (exit {out.returncode}). Press t to type it.{OFF}")
        return None
    say(f"{GRN}  heard: {transcript!r}{OFF}")
    st.log(f"{label} query heard: {transcript!r}")
    st.history.append({"role": "human", "text": transcript})
    return transcript


def decide(st, query, label, include_live=False):
    cmd = [PY, str(REPO_ROOT / "brain" / "decide.py"), query]
    if include_live:
        cmd.append("--include-live")
    out = subprocess.run(cmd, cwd=REPO_ROOT, capture_output=True, text=True)
    if out.returncode != 0:
        say(f"{RED}  decide.py exit {out.returncode}: {out.stderr.strip()}{OFF}")
        return None
    decision = json.loads(out.stdout)
    DECISION_DIR.mkdir(parents=True, exist_ok=True)
    path = DECISION_DIR / f"{label}.json"
    path.write_text(json.dumps(decision, indent=2))
    ev = decision["evidence"]
    say(f"{GRN}  tier={decision['tier']} matched={decision['matched_task_id']} "
        f"score={decision['match_score']}{OFF}")
    say(f"{DIM}  evidence: {json.dumps(ev)[:300]}{OFF}")
    st.log(f"{label} decision: tier={decision['tier']} matched={decision['matched_task_id']} "
           f"slots={json.dumps(decision['utterance_slots'])}")
    return path, decision


AFFIRMATIVE = {
    "go", "ahead", "yes", "yeah", "yep", "majority", "continue", "proceed",
    "ok", "okay", "sure", "affirmative", "try", "anyway", "do",
}
NEGATIVE = {
    "stop", "no", "nope", "wait", "hold", "cancel", "abort", "halt",
    "negative", "don't", "dont", "never",
}


def classify_reply(text):
    """Computed intent match, no LLM. Token overlap against two fixed word sets.

    A reply that hits BOTH sets ("don't go on") or NEITHER is unrecognized on
    purpose — the safe default when the human's intent is unclear is to ask
    again, not to guess and move an arm.
    """
    tokens = {
        "".join(c for c in w if c.isalpha() or c == "'")
        for w in (text or "").lower().split()
    }
    tokens.discard("")
    aff = tokens & AFFIRMATIVE
    neg = tokens & NEGATIVE
    if aff and not neg:
        return "affirmative", sorted(aff)
    if neg and not aff:
        return "negative", sorted(neg)
    return "unrecognized", sorted(aff | neg)


def resolve_with_human(st, expected, label, max_retries=2):
    """Capture a spoken reply and classify it. Retries on an unrecognized reply,
    then falls back to a typed prompt. Returns 'affirmative' or 'negative'."""
    for attempt in range(max_retries + 1):
        reply = capture_query(st, expected, f"{label}-reply{attempt or ''}")
        verdict, hits = classify_reply(reply or "")
        say(f"{DIM}  reply {reply!r} -> {verdict}"
            f"{' on ' + ', '.join(hits) if hits else ''}{OFF}")
        st.log(f"{label} reply {reply!r} -> {verdict} (matched {hits})")
        if verdict != "unrecognized":
            return verdict
        if attempt < max_retries:
            say(f"{YEL}  robot: \"I did not understand that. Stop, or go on?\"{OFF}")
        else:
            say(f"{YEL}  two retries used — switching to typed input for this reply{OFF}")
            st.text_mode = True
    reply = capture_query(st, expected, f"{label}-reply-typed")
    verdict, _ = classify_reply(reply or "")
    return "negative" if verdict != "affirmative" else "affirmative"


def llm_phrase(st, decision_path, timeout=2.0, steer=None):
    """Ask voice/llm_phrase.py to word this decision. Returns text or None.

    The LLM phrases; it never decides. Motion is driven by the computed tier in
    respond_to(), which never reads this function's output.
    """
    if not st.use_llm:
        return None
    hist_path = DECISION_DIR / "_history.json"
    hist_path.write_text(json.dumps(st.history[-6:], indent=2))
    cmd = [PY, str(REPO_ROOT / "voice" / "llm_phrase.py"), str(decision_path),
           "--history", str(hist_path), "--timeout", str(timeout)]
    if steer:
        cmd += ["--steer", steer]
    out = subprocess.run(cmd, cwd=REPO_ROOT, capture_output=True, text=True)
    note = out.stderr.strip().splitlines()[-1] if out.stderr.strip() else ""
    if out.returncode != 0 or not out.stdout.strip():
        say(f"{DIM}  [template] {note}{OFF}")
        return None
    say(f"{DIM}  {note}{OFF}")
    return out.stdout.strip()


def speak(st, decision_path, label, template=None, allow_llm=False, steer=None):
    if allow_llm:
        phrased = llm_phrase(st, decision_path, steer=steer)
        if phrased:
            cmd = [PY, str(REPO_ROOT / "voice" / "speak.py"), "--say", phrased]
            if st.no_audio:
                cmd.append("--no-audio")
            out = subprocess.run(cmd, cwd=REPO_ROOT, capture_output=True, text=True)
            spoken = out.stdout.strip()
            say(f"{BOLD}  SPOKEN [llm]: {spoken}{OFF}")
            st.log(f"{label} spoken [llm]: {spoken!r}")
            st.history.append({"role": "robot", "text": spoken})
            return
    cmd = [PY, str(REPO_ROOT / "voice" / "speak.py"), str(decision_path)]
    if template:
        cmd += ["--template", template]
    if st.no_audio:
        cmd.append("--no-audio")
    t0 = time.time()
    out = subprocess.run(cmd, cwd=REPO_ROOT, capture_output=True, text=True)
    dt = time.time() - t0
    spoken = out.stdout.strip()
    if out.returncode != 0 and template:
        # Agent D owns voice/speak.py's templates and may not have landed this one
        # yet. Degrade to tier inference rather than dying mid-beat, and say so.
        say(f"{YEL}  template '{template}' not available in voice/speak.py yet "
            f"(Agent D is authoring it) — falling back to the tier's default{OFF}")
        st.log(f"{label}: template '{template}' PENDING from Agent D, used tier default")
        return speak(st, decision_path, label)
    if out.returncode != 0:
        say(f"{RED}  speak.py exit {out.returncode}: {out.stderr.strip()}{OFF}")
        return
    if spoken:
        say(f"{BOLD}  SPOKEN [template] ({dt:.2f}s): {spoken}{OFF}")
        st.history.append({"role": "robot", "text": spoken})
    else:
        say(f"{DIM}  (act tier: says nothing — that is the point){OFF}")
    st.log(f"{label} spoken ({dt:.2f}s): {spoken!r}")


def panel(st, decision_path, label):
    """Evidence screen. Live: a fullscreen window in its own process, so plt.show()
    blocking there never blocks the state machine. Rehearse: rendered to disk."""
    close_panel(st)
    out_png = PANEL_DIR / f"{label}.png"
    cmd = [PY, str(REPO_ROOT / "voice" / "evidence.py"), str(decision_path), "--out", str(out_png)]
    if st.rehearse:
        r = subprocess.run(cmd, cwd=REPO_ROOT, capture_output=True, text=True)
        ok = r.returncode == 0 and out_png.exists()
        say(f"{DIM}  [rehearse] evidence panel -> {out_png} ({'ok' if ok else 'FAILED'}){OFF}")
        if not ok:
            say(f"{RED}  {r.stderr.strip()}{OFF}")
        st.log(f"{label} panel: {out_png} ok={ok}")
        return
    st.panel_proc = subprocess.Popen(cmd + ["--show"], cwd=REPO_ROOT)
    say(f"{DIM}  evidence panel up (pid {st.panel_proc.pid}){OFF}")


def close_panel(st):
    if st.panel_proc and st.panel_proc.poll() is None:
        st.panel_proc.terminate()
    st.panel_proc = None


def arm_motion(st, kind, name, seconds, path=None):
    """kind is 'gesture' or 'replay' (replay takes an explicit trajectory path).

    Per user override, motions are NO LONGER gated on their own keypress — the
    beat's logic decides when they run (including in response to a spoken reply).
    Ctrl-C freeze-and-hold remains the e-stop, so the banner below is printed
    immediately before any motion starts.
    """
    if st.sim_arm:
        say(f"{DIM}  [sim-arm] would run {kind} {name} (~{seconds}s) — "
            f"hardware not commanded{OFF}")
        st.log(f"arm {kind} {name}: SKIPPED (--sim-arm)")
        time.sleep(0.1)
        return

    from arm import arm_io
    from arm.safety import ArmFrozen, MotionAborted

    say(f"{RED}{BOLD}  >>> ARM MOVING NOW: {kind} {name} (~{seconds}s) — "
        f"Ctrl-C freezes and holds <<<{OFF}")
    say(f"{YEL}  arm: {kind} {name} (~{seconds}s, {arm_io.backend_name()}){OFF}")
    t0 = time.time()
    try:
        if kind == "gesture":
            arm_io.gesture(name)
        elif path is not None:
            arm_io.replay(path)
        else:
            arm_io.replay(arm_io.TASK_DEMO_PATH)
    except (KeyboardInterrupt, MotionAborted):
        say(f"{RED}  MOTION FROZEN AND HOLDING. It did NOT home. Press h to home at 25%.{OFF}")
        st.log(f"arm {name}: FROZEN by operator")
        return
    except ArmFrozen:
        say(f"{RED}  arm is frozen from an earlier abort. Press h to home first.{OFF}")
        return
    except BaseException as exc:  # noqa: BLE001
        # The arm is the weakest link on stage. NOTHING it does may stop the demo:
        # audio and the evidence panels carry the show on their own. Deliberately
        # not latched — Agent C's auto-reconnect may bring it back, so every later
        # motion tries again.
        say(f"{RED}{BOLD}  [ARM OFFLINE — continuing without motion]{OFF}")
        say(f"{DIM}  {type(exc).__name__}: {exc}{OFF}")
        st.log(f"arm {kind} {name}: OFFLINE ({type(exc).__name__}: {exc})")
        return
    dt = time.time() - t0
    say(f"{GRN}  arm: {name} complete ({dt:.1f}s){OFF}")
    st.log(f"arm {kind} {name}: complete in {dt:.1f}s")


def _reset_live_entry(query):
    """ingest.py APPENDS takes to live_index.json by design (a real corpus grows).
    On stage that means a rehearsal's takes are still counted and beat 4 says
    "I watched your 6 attempts" after recording 3. Each demo run starts this
    query's live evidence from empty so the spoken number is this run's number."""
    path = REPO_ROOT / "feedback" / "live_index.json"
    if not path.exists():
        return
    try:
        idx = json.loads(path.read_text())
    except (OSError, json.JSONDecodeError):
        return
    if idx.pop(query, None) is not None:
        path.write_text(json.dumps(idx, indent=2))


def ingest_live(st, query):
    """BEAT 4's ingest. Live: the real webcam path. Rehearse: the synthetic path,
    driven through feedback/'s own capture/extract/index functions so the parquet
    and live_index.json come out of the identical code, keyed on the real query."""
    _reset_live_entry(query)
    if not st.rehearse:
        cmd = [PY, str(REPO_ROOT / "feedback" / "ingest.py"),
               "--task", query, "--record", "3", "--demonstrators", "1"]
        r = subprocess.run(cmd, cwd=REPO_ROOT)
        if r.returncode != 0:
            say(f"{RED}  ingest exited {r.returncode} — most likely camera permission.{OFF}")
            say(f"{RED}  Narrate the beat instead: the pipeline is the same one that "
                f"produced all 424 corpus clips.{OFF}")
            return False
        st.log("beat4 ingest: 3 live webcam takes recorded")
        return True

    import time as _t

    sys.path.insert(0, str(REPO_ROOT / "feedback"))
    import capture
    import extract_shim
    import index as live_index
    import pyarrow.parquet as pq

    say(f"{DIM}  [rehearse] synthetic ingest via feedback/capture.synthetic_frame_sequence "
        f"(no camera in this session; see FACTS.md WEBCAM_STATUS){OFF}")
    slug = "".join(c if c.isalnum() else "_" for c in query.lower()).strip("_")
    out_dir = REPO_ROOT / "feedback" / "live_corpus" / slug
    out_dir.mkdir(parents=True, exist_ok=True)
    records = []
    for i in range(1, 4):
        frames = capture.synthetic_frame_sequence(duration_s=5.0)
        rows = extract_shim.add_speeds(extract_shim.process_frames(frames))
        clip_id = f"{slug}_rehearse_{int(_t.time())}_{i}"
        table = extract_shim.build_table(rows, clip_id=clip_id, task_id=slug)
        p = out_dir / f"{clip_id}.parquet"
        pq.write_table(table, p, compression="zstd")
        records.append((str(p.relative_to(REPO_ROOT)), live_index.compute_take_stats(table)))
    entry = live_index.update_index(
        REPO_ROOT / "feedback" / "live_index.json", query, records, n_demonstrators=1)
    say(f"{DIM}  [rehearse] live_stat_line: {entry['live_stat_line']}{OFF}")
    st.log(f"beat4 ingest (synthetic): 3 takes, live_stat_line={entry['live_stat_line']!r}")
    return True


# ------------------------------------------------------------------------ beats

def step(st, prompt, fn, is_motion=False):
    while True:
        if gate(st, prompt, is_motion=is_motion) == "go":
            result = fn()
            if result is not False:
                return result
            if st.rehearse:
                return result
            say(f"{YEL}  step did not complete. r retries, SPACE moves on anyway.{OFF}")
        # 'again' falls through to re-prompt


def beat1(st):
    banner("BEAT 1 / act — a task it has enough agreement about to just do it")
    q = step(st, "capture the query (say: 'garment iron press')",
             lambda: capture_query(st, BEAT1_QUERY, "beat1"))
    if q is None:
        return
    got = step(st, "compute the decision", lambda: decide(st, q, "beat1"))
    if got is None:
        return
    path, dec = got
    step(st, "the arm acts, silently — replay task_demo (~19.4s), then evidence screen",
         lambda: (arm_motion(st, "replay", "task_demo", 19.4),
                  speak(st, path, "beat1"), panel(st, path, "beat1")))


def beat2(st):
    banner("BEAT 2 / ask — majority vs outlier, and it refuses to overclaim")
    q = step(st, "capture the query (say: 'garment inside out')",
             lambda: capture_query(st, BEAT2_QUERY, "beat2"))
    if q is None:
        return
    got = step(st, "compute the decision", lambda: decide(st, q, "beat2"))
    if got is None:
        return
    path, dec = got
    step(st, "gesture 'attention', ask the question, show the split (8 vs 1, silhouette, p)",
         lambda: (arm_motion(st, "gesture", "attention", 3.4),
                  speak(st, path, "beat2"), panel(st, path, "beat2")))
    say(f"{DIM}  Say out loud: p is 0.11. With 9 clips it cannot rule out chance, and it "
        f"says so rather than dressing up a k=2 split as a finding.{OFF}")
    _resolve_ask(st, path, "beat2")

    if st.rehearse:
        # Rehearsal-only: walk the OTHER branch too, so one pass proves both.
        say(f"{DIM}  [rehearse] replaying the resolution on the affirmative branch{OFF}")
        _resolve_ask(st, path, "beat2b")


def _resolve_ask(st, path, label):
    """The ambiguity is resolved by the human, out loud. Stop or go on."""
    verdict = resolve_with_human(st, "go on", label)
    if verdict == "affirmative":
        say(f"{DIM}  Say out loud: strategy selection is real; the arm's repertoire is "
            f"one trajectory. Same replay as beat 1, honestly.{OFF}")
        arm_motion(st, "replay", "task_demo", 19.4)
    else:
        say(f"{GRN}  human said stop — the arm holds and does not execute{OFF}")
        speak(st, path, f"{label}-hold", template="ask_hold")


INSTRUCTION_FALLBACK = (
    "grab the bottle by the neck, swing it up and let go so it spins once, "
    "then catch it flat on the base"
)


def _instruction_slots(instruction):
    """Computed facts about what the human said. Measured, never asserted:
    nothing here claims the attempt worked, only that words were received."""
    # Slot names are Agent D's, taken from voice/speak.py's attempt_result
    # template — D authors the wording, run_demo only supplies measured values.
    words = [w for w in instruction.split() if w.strip()]
    return {
        "n_instruction_words": len(words),
        "instruction_chars": len(instruction),
        "n_matching_demos": 0,
    }


def _augment_decision(path, extra_slots, label):
    """Write a copy of the decision JSON with extra COMPUTED slots merged into
    utterance_slots, so voice/speak.py can interpolate them without brain/ having
    to know about the teaching loop. evidence gets the same numbers for the panel."""
    decision = json.loads(Path(path).read_text())
    decision["utterance_slots"] = {**decision.get("utterance_slots", {}), **extra_slots}
    decision["evidence"] = {**decision.get("evidence", {}), **extra_slots}
    out = DECISION_DIR / f"{label}.json"
    out.write_text(json.dumps(decision, indent=2))
    return out


def _attempt_gesture(st):
    """Prefer Agent C's 'attempt' gesture; fall back to task_demo until it lands.
    Returns (name, approx_seconds, fell_back)."""
    if st.sim_arm:
        gdir = REPO_ROOT / "arm" / "gestures"
    else:
        from arm import arm_io
        gdir = Path(arm_io.GESTURE_DIR)
    # Replayed by explicit path rather than gesture(name), so it works the moment
    # C drops attempt.json in — without waiting for arm_io.GESTURE_NAMES to list it.
    if (gdir / "attempt.json").exists():
        return "attempt", 8.0, gdir / "attempt.json", False
    return "task_demo", 19.4, gdir / "task_demo.json", True


def teach_and_attempt(st, path, label):
    """The teaching loop: it asked how, the human tells it, it tries, then it
    reports honestly what it actually has. Shared by BEAT 3 and converse mode."""
    instruction = capture_query(st, INSTRUCTION_FALLBACK, f"{label}-instruction", seconds=6)
    if not instruction:
        say(f"{RED}  no instruction captured — press r to retry or SPACE to skip{OFF}")
        return False
    slots = _instruction_slots(instruction)
    taught_path = _augment_decision(path, slots, f"{label}-attempt")
    say(f"{DIM}  computed from the instruction: {json.dumps(slots)}{OFF}")
    st.log(f"{label} instruction {instruction!r} -> slots {json.dumps(slots)}")

    # It tries. Told, not shown — and the close says exactly that.
    name, seconds, traj, fell_back = _attempt_gesture(st)
    arm_motion(st, "replay", name, seconds, path=traj)
    if fell_back:
        say(f"{YEL}  NOTE: attempt.json not present (Agent C authors it) — fell back to "
            f"task_demo. Disclose that on stage if it ships this way.{OFF}")
    speak(st, taught_path, f"{label}-attempt", template="attempt_result")
    say(f"{DIM}  Say out loud: it was told, not shown. It heard the words and moved; it "
        f"still has zero demonstrations. Nothing about that motion is evidence it "
        f"succeeded.{OFF}")
    return True


def beat3(st):
    banner("BEAT 3 / abstain — the centerpiece", RED)
    q = step(st, "capture the query (say: 'do a bottle flip')",
             lambda: capture_query(st, BEAT3_QUERY, "beat3"))
    if q is None:
        return
    st.beat3_query = q
    got = step(st, "compute the decision", lambda: decide(st, q, "beat3"))
    if got is None:
        return
    path, dec = got
    if dec["tier"] != "abstain":
        say(f"{RED}  *** tier is {dec['tier']}, expected abstain. This is the "
            f"stop-the-line case. ***{OFF}")
    # The refusal now ENDS with a question — "How do I do it?" — so the beat opens
    # a teaching loop instead of closing the door. Template is D's 'abstain_howto'.
    step(st, "gesture 'decline' (~7.4s), refuse AND ask how, show the coverage panel",
         lambda: (arm_motion(st, "gesture", "decline", 7.4),
                  speak(st, path, "beat3", template="abstain_howto"),
                  panel(st, path, "beat3")))
    say(f"{DIM}  Say out loud: it checks whether every word in the request is something it "
        f"has seen, not whether the sentence looks similar. 'flip' appears in zero of the "
        f"50 task names.{OFF}")

    step(st, "tell it how (6s), and watch it try",
         lambda: teach_and_attempt(st, path, "beat3"))


def beat4(st):
    banner("BEAT 4 / feedback — more data changes what it knows, not what it can do")
    q = st.beat3_query or BEAT3_QUERY
    ok = step(st, f"record 3 live demonstrations of {q!r}", lambda: ingest_live(st, q))
    got = step(st, "recompute with the live demos folded in",
               lambda: decide(st, q, "beat4", include_live=True))
    if got is None:
        return
    path, dec = got
    n_live = dec["evidence"].get("n_live_demos")
    if not n_live:
        say(f"{RED}  live_index had no entry for {q!r} — beat 4 will speak the plain "
            f"abstain. (ingest --task must use this exact string.){OFF}")
    step(st, "gesture 'point_screen' (~7.4s), speak the post-feedback refusal, show the panel",
         lambda: (arm_motion(st, "gesture", "point_screen", 7.4),
                  speak(st, path, "beat4"), panel(st, path, "beat4")))
    say()
    say(f"{BOLD}  CLOSE: \"More data changed what I know, not what I can do. "
        f"That is the honest boundary.\"{OFF}")


BEATS = [beat1, beat2, beat3, beat4]


# ----------------------------------------------------------------- golden path

GOLDEN_QUERY = "fold a piece of paper"
SCRIPTED_DIR = DECISION_DIR / "scripted"
AUDIO_CACHE = REPO_ROOT / "demo" / "audio_cache"


def _wake_motion(st):
    """Agent C's 'wake' showcase gesture; 'attention' stands in until it lands."""
    if st.sim_arm:
        gdir = REPO_ROOT / "arm" / "gestures"
    else:
        from arm import arm_io
        gdir = Path(arm_io.GESTURE_DIR)
    if (gdir / "wake.json").exists():
        return "wake", 18.0, gdir / "wake.json", False
    return "attention", 3.4, gdir / "attention.json", True


def golden_path(st):
    """The demo as the user wants it run: wake, greet, then free conversation
    opening on 'fold a piece of paper'. Everything after the greeting is the same
    converse loop, so judges can ask it anything without leaving the flow."""
    banner("GOLDEN PATH", GRN)
    name, seconds, traj, fell_back = _wake_motion(st)
    arm_motion(st, "replay", name, seconds, path=traj)
    if fell_back:
        say(f"{YEL}  NOTE: wake.json not present yet (Agent C authors it) — used "
            f"'attention' as the placeholder.{OFF}")

    got = decide(st, GOLDEN_QUERY, "_greeting")
    if got is not None:
        speak(st, got[0], "greeting", template="greeting")

    st.converse_script = [GOLDEN_QUERY]
    converse(st)


# -------------------------------------------------------------------- can beat

CAN_QUERY = "put this can upside down"
CAN_STEER = (
    "The human is holding a physical can in front of you and you are reaching toward it. "
    "Ask specifically whether you should hold it at the TOP or at the BOTTOM, and ask them "
    "to tell you how. Do not claim you know how to do the task."
)
GRIP_TOP = {"top", "lid", "rim", "neck", "opening", "above"}
GRIP_BOTTOM = {"bottom", "base", "side", "underneath", "below", "under"}


def _tokens(text):
    toks = {"".join(c for c in w if c.isalpha()) for w in (text or "").lower().split()}
    toks.discard("")
    return toks


def mentions_can(text):
    """Computed route to the can beat. 'can' as an OBJECT, not the auxiliary verb:
    it must not be the first word, and must not be followed by 'you'."""
    words = [w.strip(".,!?").lower() for w in (text or "").split()]
    for i, w in enumerate(words):
        if w == "can" and i > 0 and (i + 1 >= len(words) or words[i + 1] != "you"):
            return True
    return False


def classify_grip(text):
    """Keyword match, no LLM — THIS is what selects the motion, not the model."""
    toks = _tokens(text)
    top, bottom = toks & GRIP_TOP, toks & GRIP_BOTTOM
    if top and not bottom:
        return "top", sorted(top)
    if bottom and not top:
        return "bottom", sorted(bottom)
    return None, sorted(top | bottom)


def _gesture(st, name, fallback, seconds):
    """Resolve a gesture path, falling back until Agent C authors the real one."""
    if st.sim_arm:
        gdir = REPO_ROOT / "arm" / "gestures"
    else:
        from arm import arm_io
        gdir = Path(arm_io.GESTURE_DIR)
    if (gdir / f"{name}.json").exists():
        return name, seconds, gdir / f"{name}.json", False
    return fallback, seconds, gdir / f"{fallback}.json", True


def can_beat(st, transcript, label="can"):
    """Operator holds up a can. It abstains, reaches, asks HOW to hold it, and the
    answer — matched by keyword, never by the LLM — picks which grip motion runs."""
    banner("CAN BEAT — a physical object it has never been shown", CYAN)
    got = decide(st, transcript, label)
    if got is None:
        return False
    path, dec = got
    if dec["tier"] != "abstain":
        say(f"{YEL}  expected abstain for {transcript!r}, got {dec['tier']}{OFF}")

    name, secs, traj, fb = _gesture(st, "approach_can", "attention", 6.0)
    arm_motion(st, "replay", name, secs, path=traj)
    if fb:
        say(f"{YEL}  NOTE: approach_can.json not authored yet (Agent C) — used "
            f"'attention' as a placeholder.{OFF}")

    speak(st, path, f"{label}-grip-q", template="can_grip_question",
          allow_llm=True, steer=CAN_STEER)

    grip, hits, answer = None, [], ""
    for attempt in range(2):
        answer = capture_query(st, "hold it at the top", f"{label}-grip{attempt or ''}",
                               seconds=6) or ""
        grip, hits = classify_grip(answer)
        say(f"{DIM}  grip answer {answer!r} -> {grip or 'unrecognized'}"
            f"{' on ' + ', '.join(hits) if hits else ''}{OFF}")
        st.log(f"{label} grip answer {answer!r} -> {grip} (matched {hits})")
        if grip:
            break
        if attempt == 0:
            say(f"{YEL}  robot: \"Top or bottom?\"{OFF}")
    if not grip:
        grip = "top"
        say(f"{YEL}  still unrecognized — defaulting to TOP and saying so{OFF}")
        st.log(f"{label} grip defaulted to top after 2 unrecognized answers")

    gname, gsecs, gtraj, gfb = _gesture(st, f"can_grip_{grip}", "attempt", 8.0)
    arm_motion(st, "replay", gname, gsecs, path=gtraj)
    if gfb:
        say(f"{YEL}  NOTE: can_grip_{grip}.json not authored yet (Agent C) — used "
            f"'attempt' as a placeholder.{OFF}")

    slots = _instruction_slots(answer)
    closed = _augment_decision(path, slots, f"{label}-close")
    say(f"{DIM}  computed from the grip instruction: {json.dumps(slots)}{OFF}")
    speak(st, closed, f"{label}-close", template="attempt_result")
    say(f"{DIM}  Say out loud: the words were phrased by a model, but the grip that just "
        f"ran was chosen by a keyword match on your answer — not by the model.{OFF}")
    return True


# ------------------------------------------------------------------- flip beat

PICKUP_WORDS = {"pick", "pickup", "grab", "lift", "take", "hold"}
FLIP_WORDS = {"flip", "toss", "throw", "spin", "flick"}
RELEASE_TOP = {"top", "up", "upward", "upwards", "above", "high", "apex"}
FLIP_STEER = (
    "You are physically holding a can and were just told to flip it. You do not know how "
    "to flip anything — say you don't know how to do that, and end by asking how to do it. "
    "Do not claim you know how."
)


def say_line(st, text, label):
    """A fixed line through speak.py --say — same voice, no decision JSON."""
    cmd = [PY, str(REPO_ROOT / "voice" / "speak.py"), "--say", text]
    if st.no_audio:
        cmd.append("--no-audio")
    out = subprocess.run(cmd, cwd=REPO_ROOT, capture_output=True, text=True)
    spoken = out.stdout.strip() or text
    say(f"{BOLD}  SPOKEN [fixed]: {spoken}{OFF}")
    st.log(f"{label} spoken [fixed]: {spoken!r}")
    st.history.append({"role": "robot", "text": spoken})


def _put_down(st, label, why):
    """The human said no while the arm holds the can: put it down gently."""
    say(f"{GRN}  {why} — releasing the can gently, no fling{OFF}")
    st.log(f"{label}: {why}; can_release ran instead of can_fling")
    say_line(st, "Putting it down.", f"{label}-down")
    name, secs, traj, fb = _gesture(st, "can_release", "attempt", 5.0)
    arm_motion(st, "replay", name, secs, path=traj)
    if fb:
        say(f"{YEL}  NOTE: can_release.json missing — 'attempt' ran instead; the jaws "
            f"did NOT open. Ctrl-C and recover by hand.{OFF}")
    return True


def flip_beat(st, transcript, label="flip"):
    """Pick the can up FOR REAL (can_pickup grips at 17 N and holds), get told to
    flip, honestly abstain — 'flip' matches zero of the 50 task names — then take
    'hold it at the top' as the instruction and run can_fling: release on the way
    up. The can not landing is the expected, disclosed outcome. Keywords pick
    every motion; the LLM only words the computed decisions."""
    banner("FLIP BEAT — a real grip, an honest refusal, a release on the way up", CYAN)
    decide(st, transcript, label)

    say_line(st, "Picking it up. Center the can under the jaws while I hover.",
             f"{label}-pickup")
    name, secs, traj, fb = _gesture(st, "can_pickup", "approach_can", 14.0)
    arm_motion(st, "replay", name, secs, path=traj)
    if fb:
        say(f"{YEL}  NOTE: can_pickup.json missing — approach_can pantomime ran instead; "
            f"nothing is actually held.{OFF}")

    heard = None
    for attempt in range(2):
        ans = capture_query(st, "flip", f"{label}-cmd{attempt or ''}", seconds=6) or ""
        toks = _tokens(ans)
        if toks & FLIP_WORDS:
            heard = ans
            break
        # "hold" excluded: it names the grip in this beat ("keep holding"), so it
        # cannot count as a stop-word here — same reasoning as classify_reply's
        # both-sets-unrecognized rule, applied to this beat's vocabulary.
        if (toks & NEGATIVE) - {"hold"}:
            return _put_down(st, label, "human declined at the flip prompt")
        if attempt == 0:
            say_line(st, "I am holding the can. What should I do with it?", f"{label}-reask")
    if heard is None:
        heard = "flip"
        say(f"{YEL}  no flip-word heard after 2 tries — proceeding with the golden line "
            f"and saying so is on you{OFF}")

    got = decide(st, heard, f"{label}-flip")
    if got is not None:
        path, _dec = got
        speak(st, path, f"{label}-flip", template="abstain_howto",
              allow_llm=True, steer=FLIP_STEER)
        panel(st, path, f"{label}-flip")
    else:
        path = _not_understood_decision()
        say_line(st, "I don't know how to do that. How do I do it?", f"{label}-flip")

    # Same discipline as classify_reply: a reply hitting BOTH sets ("no, don't
    # throw it up") is unrecognized — ask again, never guess toward a throw.
    # "hold" is this beat's grip word, not a stop word.
    answer, verdict = "", None
    for attempt in range(3):
        answer = capture_query(st, "hold it at the top", f"{label}-how{attempt or ''}",
                               seconds=6) or ""
        toks = _tokens(answer)
        top, neg = toks & RELEASE_TOP, (toks & NEGATIVE) - {"hold"}
        say(f"{DIM}  release answer {answer!r} -> top={sorted(top)} neg={sorted(neg)}{OFF}")
        st.log(f"{label} release answer {answer!r} -> top={sorted(top)} neg={sorted(neg)}")
        if top and not neg:
            verdict = "go"
            break
        if neg and not top:
            verdict = "down"
            break
        if attempt == 0:
            say_line(st, "Tell me where to hold it.", f"{label}-how-reask")
        elif attempt == 1:
            say_line(st, "Say top and I let it go on the way up. Say stop and I put "
                         "it down.", f"{label}-how-reask2")
    if verdict == "down":
        return _put_down(st, label, "human declined the release")
    if verdict is None:
        # Unrecognized three times: the safe default is the gentle put-down, not
        # the throw — the inverse of can_beat's default-to-top, because here the
        # default moves a held object fast.
        say(f"{YEL}  three unrecognized answers — putting the can down instead of "
            f"guessing toward a throw{OFF}")
        return _put_down(st, label, "release defaulted to put-down after 3 unrecognized")

    say_line(st, "Hold it at the top and let go on the way up. If it does not land, "
                 "that is the data.", f"{label}-ack")
    fname, fsecs, ftraj, ffb = _gesture(st, "can_fling", "attempt", 10.0)
    arm_motion(st, "replay", fname, fsecs, path=ftraj)
    if ffb:
        say(f"{YEL}  NOTE: can_fling.json missing — 'attempt' ran instead.{OFF}")

    slots = _instruction_slots(answer or "hold it at the top")
    closed = _augment_decision(path, slots, f"{label}-close")
    say(f"{DIM}  computed from the instruction: {json.dumps(slots)}{OFF}")
    speak(st, closed, f"{label}-close", template="attempt_result")
    say(f"{DIM}  Say out loud: it was told, not shown. The fling is capped at the same "
        f"joint speed limit as every other motion — whether the can lands is physics, "
        f"not a claim.{OFF}")
    return True


# ------------------------------------------------------------- scripted backup

SCRIPTED_STEPS = [
    ("wake", "greeting", "greeting", None),
    ("decline", "refusal", "abstain_howto", GOLDEN_QUERY),
    ("attempt", "close", "attempt_result", GOLDEN_QUERY),
    ("approach_can", "can_question", "can_grip_question", CAN_QUERY),
    ("can_grip_top", "can_close", "attempt_result", None),
]


def _scripted_decision_path(kind):
    return SCRIPTED_DIR / f"{kind}.json"


def build_scripted_cache(st):
    """Pre-synthesize the golden path so the backup needs no network on stage.

    The NUMBERS in the cached audio are still real: the decision JSONs are
    generated here by the real brain/decide.py, not written by hand.
    """
    import importlib.util
    spec = importlib.util.spec_from_file_location("sp", REPO_ROOT / "voice" / "speak.py")
    sp = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(sp)

    SCRIPTED_DIR.mkdir(parents=True, exist_ok=True)
    AUDIO_CACHE.mkdir(parents=True, exist_ok=True)

    base = subprocess.run([PY, str(REPO_ROOT / "brain" / "decide.py"), GOLDEN_QUERY],
                          cwd=REPO_ROOT, capture_output=True, text=True)
    decision = json.loads(base.stdout)
    _scripted_decision_path("greeting").write_text(json.dumps(decision, indent=2))
    _scripted_decision_path("refusal").write_text(json.dumps(decision, indent=2))

    taught = json.loads(json.dumps(decision))
    slots = _instruction_slots(INSTRUCTION_FALLBACK)
    taught["utterance_slots"] = {**taught["utterance_slots"], **slots}
    taught["evidence"] = {**taught["evidence"], **slots}
    _scripted_decision_path("close").write_text(json.dumps(taught, indent=2))

    can_raw = subprocess.run([PY, str(REPO_ROOT / "brain" / "decide.py"), CAN_QUERY],
                             cwd=REPO_ROOT, capture_output=True, text=True)
    can = json.loads(can_raw.stdout)
    _scripted_decision_path("can_question").write_text(json.dumps(can, indent=2))
    can_closed = json.loads(json.dumps(can))
    can_slots = _instruction_slots("hold it at the top")
    can_closed["utterance_slots"] = {**can_closed["utterance_slots"], **can_slots}
    can_closed["evidence"] = {**can_closed["evidence"], **can_slots}
    _scripted_decision_path("can_close").write_text(json.dumps(can_closed, indent=2))

    for _, kind, template, _q in SCRIPTED_STEPS:
        d = json.loads(_scripted_decision_path(kind).read_text())
        text, _ = sp.render(d, template_name=template)
        (AUDIO_CACHE / f"{kind}.txt").write_text(text + "\n")
        mp3 = AUDIO_CACHE / f"{kind}.mp3"
        try:
            dt = sp.synthesize_to_file(text, mp3)
            say(f"{GRN}  cached {mp3.name} ({mp3.stat().st_size} bytes, {dt:.2f}s){OFF}")
        except Exception as exc:  # noqa: BLE001
            say(f"{RED}  could not pre-synthesize {kind}: {exc}{OFF}")
            say(f"{YEL}  scripted mode will fall back to macOS 'say' for this line{OFF}")
    return True


def scripted_backup(st):
    """Fully deterministic backup: no mic, no LLM, no network, no ElevenLabs call.
    Sanctioned by the judge AS A BACKUP — so it is labelled as one on screen."""
    banner("[SCRIPTED BACKUP] — deterministic, no mic / no LLM / no network", YEL)
    say(f"{YEL}  This is the sanctioned backup path. Say so out loud: the numbers in it "
        f"are real (generated by brain/decide.py), the timing is not live.{OFF}")

    for gesture_name, kind, _template, operator_line in SCRIPTED_STEPS:
        cue = {
            "refusal": f'OPERATOR SAYS: "{GOLDEN_QUERY}"',
            "close": "OPERATOR describes how to fold paper (freely, ~6s)",
            "can_question": f'OPERATOR holds up the can and SAYS: "{CAN_QUERY}"',
            "can_close": 'OPERATOR SAYS: "hold it at the top"',
        }.get(kind)
        if cue:
            say()
            say(f"{BOLD}  {cue}{OFF}")
        if gate(st, f"[SCRIPTED BACKUP] {kind}: gesture '{gesture_name}' then cached audio") != "go":
            continue

        gdir = (REPO_ROOT / "arm" / "gestures") if st.sim_arm else None
        if gdir is None:
            from arm import arm_io
            gdir = Path(arm_io.GESTURE_DIR)
        traj = gdir / f"{gesture_name}.json"
        if not traj.exists():
            fb = {"wake": "attention", "approach_can": "attention",
                  "can_grip_top": "attempt", "can_grip_bottom": "attempt"}.get(
                      gesture_name, "task_demo")
            say(f"{YEL}  {gesture_name}.json missing — using {fb}{OFF}")
            traj = gdir / f"{fb}.json"
        arm_motion(st, "replay", gesture_name, 10.0, path=traj)

        mp3 = AUDIO_CACHE / f"{kind}.mp3"
        txt = (AUDIO_CACHE / f"{kind}.txt")
        line = txt.read_text().strip() if txt.exists() else ""
        say(f"{BOLD}  SPOKEN [cached]: {line}{OFF}")
        st.log(f"scripted {kind} spoken [cached]: {line!r}")
        if st.no_audio:
            continue
        if mp3.exists():
            subprocess.run(["afplay", str(mp3)])
        else:
            say(f"{YEL}  no cached mp3 — falling back to macOS say{OFF}")
            subprocess.run(["say", "-v", "Samantha", line])

    banner("[SCRIPTED BACKUP] COMPLETE", YEL)


# ---------------------------------------------------------------- converse mode

NOT_UNDERSTOOD_PATH = DECISION_DIR / "_not_understood.json"


def _not_understood_decision():
    """A decision-shaped stub so speak.py can render the no-slot fixed line
    through the identical template mechanism as everything else."""
    NOT_UNDERSTOOD_PATH.parent.mkdir(parents=True, exist_ok=True)
    NOT_UNDERSTOOD_PATH.write_text(json.dumps({
        "query": "", "tier": "abstain", "matched_task_id": None, "match_score": 0.0,
        "coverage_detail": {"covered": [], "uncovered": []},
        "evidence": {"n_matching_demos": 0}, "utterance_slots": {},
    }, indent=2))
    return NOT_UNDERSTOOD_PATH


def respond_to(st, transcript, label):
    """One conversational turn: decide, then ALWAYS speak and gesture per tier."""
    # Routed before the zero-coverage noise guard on purpose: "put this can upside
    # down" legitimately scores 0.0 (every content word is unknown), which is the
    # honest result but would otherwise be swallowed as noise.
    if mentions_can(transcript):
        if _tokens(transcript) & PICKUP_WORDS:
            return flip_beat(st, transcript, label)
        return can_beat(st, transcript, label)

    got = decide(st, transcript, label)
    if got is None:
        speak(st, _not_understood_decision(), label, template="not_understood")
        return
    path, dec = got
    tier = dec["tier"]

    # Computed, not a guess: coverage 0.0 means not one content word in the
    # utterance matched anything in 50 task names — that is noise, not a task I
    # don't know. "bottle flip" scores 0.5 and still gets the full teaching loop.
    if tier == "abstain" and not dec.get("match_score"):
        say(f"{DIM}  match_score 0.0 — no content word matched anything; treating as "
            f"noise rather than a task{OFF}")
        speak(st, _not_understood_decision(), label, template="not_understood")
        return

    if tier == "act":
        # Converse breaks the act-silent rule on purpose: in free conversation
        # silence is indistinguishable from a crash. BEAT 1 stays silent.
        speak(st, path, label, template="act_confirm", allow_llm=True)
        arm_motion(st, "replay", "task_demo", 19.4)
    elif tier == "ask":
        arm_motion(st, "gesture", "attention", 3.4)
        speak(st, path, label, allow_llm=True)
        panel(st, path, label)
        _resolve_ask(st, path, label)
    else:
        arm_motion(st, "gesture", "decline", 7.4)
        speak(st, path, label, template="abstain_howto", allow_llm=True)
        panel(st, path, label)
        teach_and_attempt(st, path, label)


def converse(st):
    """Free conversation. Listen, decide, always respond out loud, repeat.

    Every response is still a fixed template filled with numbers computed by
    brain/decide.py at runtime — no LLM. That holds in open conversation because
    decide.py already handles arbitrary queries: coverage is computed against the
    real task names whatever you say to it.
    """
    banner("CONVERSE — say anything; it answers with what it measured", GRN)
    say(f"{DIM}  q ends conversation and returns. Empty capture twice -> typed input.{OFF}")
    empty_streak = 0
    turn = 0

    scripted = list(st.converse_script) if st.rehearse else None
    while True:
        turn += 1
        if scripted is not None:
            if not scripted:
                say(f"{DIM}  [rehearse] converse script exhausted{OFF}")
                return
            st.scripted[f"converse{turn}"] = scripted.pop(0)
        elif not st.text_mode:
            say()
            say(f"{BOLD}SPACE to speak (6s), t=typed, q=end conversation{OFF}")
            k = read_key()
            if k == "q":
                say(f"{GRN}  ending conversation{OFF}")
                return
            if k == "t":
                st.text_mode = not st.text_mode
                say(f"{GRN}  input mode -> {'TYPED' if st.text_mode else 'SPOKEN'}{OFF}")
                continue

        transcript = capture_query(st, "", f"converse{turn}", seconds=6)
        if not transcript:
            empty_streak += 1
            speak(st, _not_understood_decision(), f"converse{turn}",
                  template="not_understood")
            if empty_streak >= 2 and not st.text_mode:
                say(f"{YEL}  two empty captures — switching to typed input{OFF}")
                st.text_mode = True
            continue
        empty_streak = 0
        if transcript.strip().lower() in ("quit", "stop the demo", "end conversation"):
            say(f"{GRN}  ending conversation{OFF}")
            return
        respond_to(st, transcript, f"converse{turn}")


# ------------------------------------------------------------------------- main

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--text-mode", action="store_true", help="start in typed-input mode")
    ap.add_argument("--no-audio", action="store_true", help="print the spoken text, do not play it")
    ap.add_argument("--beat", type=int, default=1, help="start at this beat (1-4)")
    ap.add_argument("--rehearse", action="store_true",
                    help="drive all 4 beats through --text non-interactively")
    ap.add_argument("--beats", action="store_true",
                    help="run the original scripted 4-beat sequence instead of the golden path")
    ap.add_argument("--scripted", action="store_true",
                    help="deterministic backup: cached audio, no mic/LLM/network")
    ap.add_argument("--build-cache", action="store_true",
                    help="pre-synthesize the scripted backup's audio, then exit")
    ap.add_argument("--no-llm", action="store_true",
                    help="force fixed templates; never call voice/llm_phrase.py")
    ap.add_argument("--converse", action="store_true",
                    help="go straight into free conversation instead of the scripted beats")
    ap.add_argument("--flip", action="store_true",
                    help="go straight into the flip beat: real can pickup -> told 'flip' -> "
                         "honest abstain -> 'hold it at the top' -> release on the way up")
    ap.add_argument("--sim-arm", action="store_true",
                    help="print what the arm would do instead of commanding it "
                         "(auto-enabled by --rehearse when the backend is real hardware)")
    args = ap.parse_args()

    # A rehearsal must never command a live arm as a side effect. Agent C added an
    # ARM_FORCE_SIM hook to arm/facts.py, so a rehearsal forces the simulator while
    # still running the REAL arm_io / motion / safety code — strictly better than
    # stubbing the arm out, which is what --sim-arm still does as an escape hatch.
    if args.rehearse and not args.sim_arm:
        os.environ["ARM_FORCE_SIM"] = "1"

    st = State(args)
    DECISION_DIR.mkdir(parents=True, exist_ok=True)
    PANEL_DIR.mkdir(parents=True, exist_ok=True)

    banner("I DON'T KNOW HOW TO DO THAT YET")
    if st.sim_arm:
        say(f"  arm backend : {YEL}STUBBED (--sim-arm){OFF} — no motion will be commanded")
    else:
        from arm import arm_io
        d = arm_io.describe()
        say(f"  arm backend : {d['backend']}  (simulated={d['simulated']}, "
            f"FACTS HARDWARE_PRESENT={d['hardware_present_facts']})")
        if not d["simulated"]:
            say(f"{RED}{BOLD}  REAL ARM. Motions are NOT individually gated: they run when "
                f"the beat decides, including in response to a spoken reply.{OFF}")
            say(f"{RED}  Ctrl-C freezes and holds. Keep the workspace clear.{OFF}")
    say(f"  input mode  : {'TYPED' if st.text_mode else 'SPOKEN (listen/transcribe.py)'}")
    say(f"  sim render  : ARM_SIM_RENDER={os.environ.get('ARM_SIM_RENDER')} "
        f"(0 = no per-motion GIF, stills already in arm/sim_out/)")
    say()
    say(f"{BOLD}  SAY THIS OUT LOUD, ONCE, EARLY:{OFF}")
    say(f"{BOLD}  \"{DISCLOSURE}\"{OFF}")

    rc = 0
    try:
        if args.build_cache:
            build_scripted_cache(st)
            return 0

        step(st, "home the arm before anything else (~1s)", lambda: _home(st), is_motion=True)

        if args.scripted:
            scripted_backup(st)
        elif args.flip:
            flip_beat(st, "pick up the can")
        elif args.converse:
            converse(st)
        elif args.beats:
            for i, beat in enumerate(BEATS, start=1):
                if i < args.beat:
                    continue
                beat(st)
        else:
            golden_path(st)

        if st.rehearse and not args.scripted:
            # One rehearsal pass covers everything: the beats and the scripted
            # backup, on top of whichever mode ran above.
            for i, beat in enumerate(BEATS, start=1):
                beat(st)
            st.converse_script = ["garment iron press", CAN_QUERY, "wubbalubba dubdub"]
            converse(st)
            scripted_backup(st)
        banner("DEMO COMPLETE", GRN)
    except Quit:
        say(f"\n{YEL}quit — arm left where it is, not homed behind your back{OFF}")
    except KeyboardInterrupt:
        say(f"\n{RED}interrupted{OFF}")
        rc = 130
    finally:
        close_panel(st)
        if st.rehearse:
            out = REPO_ROOT / "demo" / "rehearsal_transcript.txt"
            out.write_text("\n".join(st.transcript) + "\n")
            say(f"\n{DIM}rehearsal transcript -> {out}{OFF}")
    return rc


def _home(st):
    if st.sim_arm:
        say(f"{DIM}  [sim-arm] would home — hardware not commanded{OFF}")
        return
    t0 = time.time()
    try:
        from arm import arm_io
        arm_io.home()
    except BaseException as exc:  # noqa: BLE001 — see arm_motion
        say(f"{RED}{BOLD}  [ARM OFFLINE — continuing without motion]{OFF}")
        say(f"{DIM}  {type(exc).__name__}: {exc}{OFF}")
        st.log(f"arm home: OFFLINE ({type(exc).__name__})")
        return
    say(f"{GRN}  arm: home complete ({time.time() - t0:.1f}s){OFF}")
    st.log(f"arm home: complete in {time.time() - t0:.1f}s")


if __name__ == "__main__":
    sys.exit(main())
